### ISSUE TITLE
Search based on repository

### ISSUE THREAD

**Issue by eknowlton** [jhkiehna/clubhouse-github-story-linker-chrome-extension#4]
I'm not sure this is the only scenario, but usually when I'm looking for a issue; the issue is specific to the repository i'm creating the PR for.

I think it would be pretty cool if when I searched it would filter based on the repository.

**Comment by jhkiehna** [comment]
I don't know that this is possible based on clubhouse's api and the way search works. I could be wrong, but i don't think the clubhouse api returns which github repo a project is associated with. However, I can for sure search based on the clubhouse project.

so I added a filter select box that allows the user to only search within a specific clubhouse project if they want.
